version: "3.5"

services:
  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    container_name: admin_service
    env_file:
      - .env
    volumes:
      - ./database:/app/database  # Общий модуль database
      - ./utils:/app/utils
    depends_on:
      - database
      - migrations

  notifications:
    build:
      context: notifications
      dockerfile: Dockerfile
    container_name: notifications_service
    env_file:
      - .env
    volumes:
      - ./database:/app/database  # Общий модуль database
      - ./utils:/app/utils
    depends_on:
      - database
      - migrations

  database:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrations:
    build:
      context: migrations
      dockerfile: Dockerfile
    container_name: migrations_service
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
      - ./database:/app/database
      - ./utils:/app/utils
    depends_on:
      - database

volumes:
  postgres_data:
